# Generated by Django 6.0.6 on 2026-06-25 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='poster_at',
            new_name='posted_at',
        ),
    ]
